//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public string MovieSn { get; set; }
        public string MovieName { get; set; }
        public string Rate { get; set; }
        public string Actor { get; set; }
    }
}
